### PR TITLE
Fix application code not recognized when using remote development

### PR DESCRIPTION
**Pull request by notTamion**
when using remote development with for example wsl it will return JBC as the application code which is not what we actually want. I am not entirely sure whether my fix will always return a correct code as i have tested this only with intellij ultimate and the wsl instance.

### CODE REVIEW

**Comment by pygrum** [comment]
I just opened issue #208 before coming across this, can confirm JBC is returned as application code when doing remote development with GoLand (Windows host) on a Kali VM (remote).

**Comment by Azn9** [comment]
I need to check if this works for every IDE with and without the client. And Jetbrains staff never answered me if there's a good way of doing that 🥲

**Comment by notTamion** [comment]
If checking for every ide is too much work for you (can completely understand lol) we could also check whether the productCode is JBC and if that is the case use the applicationName and otherwise still use productCode, this way we aren't at risk of breaking this for normal running IDEs but still fix the issue with remote development (considering that is already broken and can't break any further)

**Comment by Azn9** [comment]
Sorry, I should have precise; what I need to check is that the application name returned by every IDE corresponds to the searched value for each IDE data.

**Comment by pygrum** [comment]
If its of any help I recompiled the plugin with this patch and now it's functioning correctly. GoLand 2024.2

**Comment by Azn9** [comment]
> If its of any help I recompiled the plugin with this patch and now it's functioning correctly. GoLand 2024.2

Seeing that some IDEs like Rider have different values for no reason I unfortunately cannot assume that this will work without any change 😅 
But thanks for the info, that's one less to test.

**Comment by notTamion** [comment]
well what i meant is that we do something like this (pseudo code):
`val applicationCode = ApplicationInfo.getInstance().build.productCode == "JBC" ? ApplicationType.IDE_EDITION.applicationName : ApplicationInfo.getInstance().build.productCode;`

ofc this still might not work for some JBC setups (which are already broken) but it will at least fix it for most without breaking any setups that don't use JBC

**Comment by notTamion** [comment]
I had time to test this with RustRover, Webstorm, Rider, Clion, Pycharm professional and had no problems. i only tested this without the JBC as i assume that ApplicationType.IDE_EDITION.applicationName is the same regardless of whether you use it with or without JBC

**Comment by Azn9** [comment]
> I had time to test this with RustRover, Webstorm, Rider, Clion, Pycharm professional and had no problems. i only tested this without the JBC as i assume that ApplicationType.IDE_EDITION.applicationName is the same regardless of whether you use it with or without JBC

❤️ thank you very much

**Comment by Azn9** [comment]
Resolved via https://github.com/Azn9/JetBrains-Discord-Integration/commit/0c068acd10a863908ae0dd8e3ce716ac79dce1d8
Thanks for your contribution tho!

**Pull request closed without merging**
